# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ExportMetadataToHTML.py
# Created on: 2017-05-17 13:44:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
metadata_testing_sample_data = "C:\\Data\\grid-garage-tests\\metadata-testing-sample-data"
Dataset = "C:\\Data\\grid-garage-tests\\metadata-testing-sample-data\\tifs\\CMA_SubRegions_CMA_SUB.tif"
ArcGIS_xsl = "C:\\Program Files (x86)\\ArcGIS\\Desktop10.4\\Metadata\\Stylesheets\\ArcGIS.xsl"
v_Name__html = "%Workspace%\\%Name%.html"
Name = "CMA_SubRegions_CMA_SUB"

# Process: Iterate Datasets
arcpy.IterateDatasets_mb(metadata_testing_sample_data, "", "", "RECURSIVE")

# Process: XSLT Transformation
arcpy.XSLTransform_conversion(Dataset, ArcGIS_xsl, v_Name__html, "")

